
name: Molecule

on:
  push:
    branches:
      - main
      - fix/RAD-614
  pull_request_target:
    types:
      - opened
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "${{ github.repository }}"
      - name: Molecule
        uses: monolithprojects/action-molecule@v1.4.1
